'use strict'

const PROTOCOL = Object.freeze({
  TCP: 'tcp'
})

const FUNCTION_CODES = Object.freeze({
  READ_COILS: 0x01,
  READ_DISCRETE_INPUTS: 0x02,
  READ_HOLDING_REGISTERS: 0x03,
  READ_INPUT_REGISTERS: 0x04,
  WRITE_SINGLE_COIL: 0x05,
  WRITE_SINGLE_REGISTER: 0x06,
  WRITE_MULTIPLE_COILS: 0x0F,
  WRITE_MULTIPLE_REGISTERS: 0x10
})

module.exports = {
  PROTOCOL,
  FUNCTION_CODES
}
